### ISSUE TITLE
示例Demo开启混淆后， java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by YuChen91** [JustKiddingBaby/FragmentRigger#10]
build.gradle文件中开启混淆
```
buildTypes {
        ...
        debug {
            minifyEnabled true
            //是否清理无用资源
            shrinkResources false
            //是否启用zipAlign压缩
            zipAlignEnabled false
            signingConfig signingConfigs.myConfig
            versionNameSuffix rootProject.ext.app.versionNameSuffix
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
```

proguard-rules.pro 配置混淆文件
```
-ignorewarnings
```
运行示例DEMO
```
12-25 17:48:11.759 32639-32639/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.yj.app, PID: 32639
                                                   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.yj.app/com.yj.app.MainActivity}: java.lang.NoSuchMethodException: getInstance []
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2569)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:192)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:224)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5929)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
                                                    Caused by: java.lang.NoSuchMethodException: getInstance []
                                                       at java.lang.Class.getMethod(Class.java:664)
                                                       at java.lang.Class.getDeclaredMethod(Class.java:626)
                                                       at com.a.a.a.b.a.b(Unknown Source)
                                                       at com.a.a.a.b.a.a(Unknown Source)
                                                       at com.a.a.a.b.a.a(Unknown Source)
                                                       at android.support.v4.app.k.a(Unknown Source)
                                                       at android.support.v4.app.k.<init>(Unknown Source)
                                                       at android.support.v7.app.d.<init>(Unknown Source)
                                                       at com.yj.app.a.a.<init>(Unknown Source)
                                                       at com.yj.app.MainActivity.<init>(Unknown Source)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1606)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2546)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755) 
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:192) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:224) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5929) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879) 
```

**Comment by JustKiddingBaby** [comment]
@YuChen91 加上`-keep public class * extends android.app.Activity`试试。

**Comment by YuChen91** [comment]
@JustKiddingBaby  加上后还是报java.lang.NoSuchMethodException

除第三方混淆，项目用的是下方这些混淆

```
-ignorewarnings

# 指定代码的压缩级别
-optimizationpasses 5
# 不使用大小写混合
-dontusemixedcaseclassnames
# 混淆时不做预校验
-dontpreverify
 # 混淆时记录日志
-verbose
 # 混淆时所采用的算法
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

 # 保持哪些类不被混淆：四大组件，应用类，配置类等等
 -keep class android.** {*; }
-keep public class * extends android.view
-keep public class * extends android.support.v4.**
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService

# 保持 native 方法不被混淆
-keepclasseswithmembernames class * {
    native <methods>;
}

 # 保持自定义控件类不被混淆
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

 # 保持自定义控件类不被混淆
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

 # 保持自定义控件类不被混淆
-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}

 # 保持枚举 enum 类不被混淆
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

 # 保持 Parcelable 不被混淆
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
 # 这个主要是在layout中写的onclick方法android:onclick="onClick"，不进行混淆
 -keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
 }

```

**Comment by JustKiddingBaby** [comment]
@YuChen91 抱歉，这两天有点忙，现在才回复你，代码混淆规则已更新。[**代码混淆Wiki**](https://github.com/JustKiddingBaby/FragmentRigger/wiki/%E4%BB%A3%E7%A0%81%E6%B7%B7%E6%B7%86)

```
-keep class com.jkb.fragment.rigger.rigger.** {*;}
-keep interface com.jkb.fragment.rigger.rigger.** {*;}

-keep public class * extends android.app.Activity
-keep public class * extends android.support.v4.app.Fragment
-keepclassmembers class * extends android.app.Activity {
   public int getContainerViewId();
   public void onRiggerBackPressed();
   public void onFragmentResult(int,int,android.os.Bundle);
   public void onLazyLoadViewCreated(android.os.Bundle);
   public int[] getPuppetAnimations();
}
-keepclassmembers class * extends android.support.v4.app.Fragment {
   public int getContainerViewId();
   public void onRiggerBackPressed();
   public void onFragmentResult(int,int,android.os.Bundle);
   public void onLazyLoadViewCreated(android.os.Bundle);
   public int[] getPuppetAnimations();
}
```

**Comment by YuChen91** [comment]
@JustKiddingBaby 十分感谢，辛苦了！

**Comment by koala0x** [comment]
-keep class com.jkb.fragment.** {*;}
