### ISSUE TITLE
UnKnown error com.yj.app.MainActivity@dd938a9is not a puppet object

### ISSUE THREAD

**Issue by zouxianbincc** [JustKiddingBaby/FragmentRigger#12]
Process: com.yj.app, PID: 18142
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yj.app/com.yj.app.MainActivity}: com.jkb.fragment.rigger.exception.RiggerException: UnKnown error com.yj.app.MainActivity@dd938a9is not a puppet object
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                    Caused by: com.jkb.fragment.rigger.exception.RiggerException: UnKnown error com.yj.app.MainActivity@dd938a9is not a puppet object
                                                       at com.jkb.fragment.rigger.rigger.Rigger.getRigger(Rigger.java:94)
                                                       at com.yj.app.MainActivity.init(MainActivity.java:14)
                                                       at com.yj.app.base.BaseActivity.onCreate(BaseActivity.java:26)
                                                       at android.app.Activity.performCreate(Activity.java:6910)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 请确认MainActivity是否添加`@Puppet`注解。
>使用该框架的基础支持是使用的类和目标类必须是被`@Puppet`标注的。

**详细使用请看[Wiki](https://github.com/JustKiddingBaby/FragmentRigger/wiki/%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8)**

**Comment by zouxianbincc** [comment]
我执行的是你的工程。
public class MainActivity extends BaseActivity {

  @Override
  protected void init(Bundle savedInstanceState) {
    Rigger.enableDebugLogging(true);
    if (savedInstanceState == null) {
      Rigger.getRigger(this).startFragment(TestFragment.newInstance());
    }
    Logger.d(this, "Activity=" + hashCode());
  }
}
基类里是有@Puppet
@Puppet(containerViewId = R.id.atyContent, bondContainerView = true)
public abstract class BaseActivity extends AppCompatActivity {

  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(getContentView());
    init(savedInstanceState);
  }

  @LayoutRes
  protected int getContentView() {
    return R.layout.activity_content;
  }

  protected abstract void init(Bundle savedInstanceState);
}

@Puppet
public abstract class BaseFragment extends Fragment {

  protected static final String BUNDLE_KEY = "/bundle/key";
  protected View mContentView;
  protected Context mContext;

  @Override
  public void onAttach(Context context) {
    super.onAttach(context);
    mContext = context;
  }

  @Nullable
  @Override
  public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
      @Nullable Bundle savedInstanceState) {
    super.onCreateView(inflater, container, savedInstanceState);
    mContentView = inflater.inflate(getContentView(), container, false);
    return mContentView;
  }

  @Override
  public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    init(savedInstanceState);
  }

  @LayoutRes
  protected abstract int getContentView();

  protected abstract void init(Bundle savedInstanceState);

  protected View findViewById(@IdRes int id) {
    return mContentView.findViewById(id);
  }
}
难道是我对AOP用得不对？需要做什么编译操作吗？因为我是导入了你的工程，

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 如果没有修改`gradle`的配置，请关闭`Instant Run`并`clean`一下项目重新尝试。Demo是没有问题的。
