### ISSUE TITLE
android studio 3.0 运行报 null

### ISSUE THREAD

**Issue by zouxianbincc** [JustKiddingBaby/FragmentRigger#15]
12-29 12:40:49.234 21724-21724/com.yj.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: com.yj.app, PID: 21724
                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yj.app/com.yj.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jkb.fragment.rigger.rigger.RiggerTransaction.setCustomAnimations(int, int)' on a null object reference
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640)
                                                                at android.app.ActivityThread.access$800(ActivityThread.java:182)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                at android.os.Looper.loop(Looper.java:194)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jkb.fragment.rigger.rigger.RiggerTransaction.setCustomAnimations(int, int)' on a null object reference
                                                                at com.jkb.fragment.rigger.rigger._Rigger.addFragmentWithAnim(_Rigger.java:417)
                                                                at com.jkb.fragment.rigger.rigger._Rigger.startFragment(_Rigger.java:243)
                                                                at com.yj.app.MainActivity.init(MainActivity.java:14)
                                                                at com.yj.app.base.BaseActivity.onCreate_aroundBody2(BaseActivity.java:26)
                                                                at com.yj.app.base.BaseActivity$AjcClosure3.run(BaseActivity.java:1)
                                                                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                                at com.jkb.fragment.rigger.aop.AspectActivityPoint.onCreateProcess(AspectActivityPoint.java:76)
                                                                at com.yj.app.base.BaseActivity.onCreate(BaseActivity.java:24)
                                                                at android.app.Activity.performCreate(Activity.java:6161)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
                                                                at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                at android.os.Looper.loop(Looper.java:194) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
12-29 12:45:49.661 21724-21724/com.yj.app I/Process: Sending signal. PID: 21724 SIG: 9

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 我早AS3.0.1上测试了，场景无法重现，请确认gradle配置是否正常，记得关闭`Instant Run`。

**Comment by zouxianbincc** [comment]
我这边是 4.1-all  3.0.1  的环境。也关了Instant Run 。但是还是跑不起来 。
在gradle_plugin_android_aspectjx 上 说  1.0.10   版本在  4.1-all  3.0.1 是有bug 的

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 目前AsPectJ是使用第三方插件的，不好进行错误排查，以后我会找时间推出自己的插件，可以的话请降低gradle版本重新尝试。

**Comment by zouxianbincc** [comment]
@JustKiddingBaby 好的。我今天也尝了自己集成aspectj 但是还是会空指针。
我更新gradle_plugin_android_aspectjx 到 1.1.1 还不是行，会出现 Error:java.lang.NoClassDefFoundError: org/aspectj/bridge/MessageHandler

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 这个框架的扩展性很好，会不断完善下去的（；

**Comment by zouxianbincc** [comment]
@JustKiddingBaby  我就是发现这个，所以一直想把代码跑起来。研究研究

**Comment by zouxianbincc** [comment]
@JustKiddingBaby 模块化开发 不同的module之间，是否考虑路由协议跳转？

**Comment by JustKiddingBaby** [comment]
@zouxianbincc Fragment本身就可以用来解耦，你可以使用`ARouter`等路由框架和本框架配合使用。
>以后可能会仿照Activity启动模式写出Fragment的启动模式+路由跳转，但是目前没有精力去实现。

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 
>已经全面对gradle3.*和gradle4.*做了兼容测试,并列举了常见的几个错误.详情请看[**Wiki**](https://github.com/JustKiddingBaby/FragmentRigger/wiki/gradle%E4%BE%9D%E8%B5%96%E9%97%AE%E9%A2%98)

**如果发现其他错误,请提交issure或者发邮件给我 ;)**
