### ISSUE TITLE
Demo MainAvtivity 返回键退出错误 

### ISSUE THREAD

**Issue by xuchengcan** [JustKiddingBaby/FragmentRigger#20]
Caused by: com.jkb.fragment.rigger.exception.RiggerException: UnKnown error com.yj.app.MainActivity@ef8c36e is not added into rigger. please check your config or contact author.
                                                                at com.jkb.fragment.rigger.rigger.Rigger.getRigger(Rigger.java:94)
                                                                at com.jkb.fragment.rigger.rigger._FragmentRigger.close(_FragmentRigger.java:298)
                                                                at com.jkb.fragment.rigger.rigger._Rigger.onBackPressed(_Rigger.java:220)
                                                                at com.jkb.fragment.rigger.rigger._Rigger.onRiggerBackPressed(_Rigger.java:201)
                                                                at com.jkb.fragment.rigger.rigger._Rigger.onBackPressed(_Rigger.java:228)
                                                                at com.jkb.fragment.rigger.rigger._Rigger.onRiggerBackPressed(_Rigger.java:201)
                                                                at com.jkb.fragment.rigger.rigger.Rigger.onBackPressed(Rigger.java:254)
                                                                at java.lang.reflect.Method.invoke(Native Method)

**Comment by JustKiddingBaby** [comment]
@xuchengcan 抱歉，在开发的时候没注意合并了dev分支，现已修复。
