### ISSUE TITLE
使用glide4.6.1点击返回键时异常

### ISSUE THREAD

**Issue by ufbeans** [JustKiddingBaby/FragmentRigger#43]
```     
Caused by: com.jkb.fragment.rigger.c.c: Can not find Puppet annotation.please add Puppet annotation for the class com.bumptech.glide.manager.SupportRequestManagerFragment
        at com.jkb.fragment.rigger.rigger.Rigger.getRigger(Unknown Source:57)
        at com.jkb.fragment.rigger.rigger._Rigger.dispatchBackPressed(Unknown Source:45)
        at com.jkb.fragment.rigger.rigger.Rigger.onBackPressed(Unknown Source:9)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.jkb.fragment.rigger.b.a.h(Unknown Source:26)
 ```

**Comment by JustKiddingBaby** [comment]
@ufbeans 感谢反馈，周末会对你提出的这种场景进行尝试，如果有问题会尽快解决。

**Comment by ufbeans** [comment]
@JustKiddingBaby 提交了。你有时间看一下

**Comment by iFanie** [comment]
@JustKiddingBaby since no one is going to use Glide fragments by hand, you could just ignore any instance of com.bumptech.glide.manager.SupportRequestManagerFragment and not throw a RiggerException
