### ISSUE TITLE
as集成出现编译问题

### ISSUE THREAD

**Issue by chenbaige** [JustKiddingBaby/FragmentRigger#5]
as编译痴线以下异常：Could not find matching constructor for: org.gradle.util.Clock()

**Comment by JustKiddingBaby** [comment]
@chenbaige 这不属于本框架的错误，应该是你装了第三方gradle的插件导致的，https://github.com/passy/build-time-tracker-plugin/issues/83 ,这里和你遇到了同样的问题，请确认是否是你想要的答案

**Comment by chenbaige** [comment]
问题是：把gradle版本降低到4.1可以成功编译。运行的时候出现如下异常是什么问题： java.lang.NoSuchMethodError: com.jkb.fragment.rigger.aop.AspectPuppetActivity.aspectOf

**Comment by JustKiddingBaby** [comment]
请贴出你根目录下的`build.gradle`和module的`build.gradle`配置，并贴出完整错误信息

**Comment by chenbaige** [comment]
project.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
//        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.8'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

app.gradle
`apply plugin: 'com.android.application'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'android-aspectjx'
//apply plugin: 'com.hujiang.android-aspectjx'
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "com.hbandroid.fragmentactivitydemo"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

aspectjx {
    //织入遍历符合条件的库
    includeJarFilter 'universal-image-loader', 'AspectJX-Demo/library'
    //排除包含‘universal-image-loader’的库
    excludeJarFilter 'universal-image-loader'
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'com.ashokvarma.android:bottom-navigation-bar:2.0.4'
//    compile 'org.aspectj:aspectjrt:1.8.9'
    compile 'com.justkiddingbaby:fragment-rigger:1.0.0'
    testCompile 'junit:junit:4.12'
}
`

exception:
` Process: com.hbandroid.fragmentactivitydemo, PID: 20195
                                                                                    java.lang.NoSuchMethodError: com.jkb.fragment.rigger.aop.AspectPuppetActivity.aspectOf
                                                                                        at com.hbandroid.fragmentactivitydemo.avtivity.MainActivity.<init>(MainActivity.java:26)
                                                                                        at java.lang.Class.newInstanceImpl(Native Method)
                                                                                        at java.lang.Class.newInstance(Class.java:1208)
                                                                                        at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2107)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335)
                                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                        at dalvik.system.NativeStart.main(Native Method)`

MainActivity:
`@Puppet(containerViewId = R.id.id_content)
public class MainActivity extends AppCompatActivity implements BottomNavigationBar.OnTabSelectedListener//异常定位在这里 {

    @BindView(R.id.tb_left_iv)
    ImageView tbLeftIv;
    @BindView(R.id.tb_cneter_tv)
    TextView tbCneterTv;
    @BindView(R.id.tb_right_tv)
    TextView tbRightTv;
    @BindView(R.id.id_content)
    FrameLayout idContent;
    @BindView(R.id.bottom_navigation_bar)
    BottomNavigationBar bottomNavigationBar;

    private Fragment[] fragments = new Fragment[4];

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
        init();
    }

    private void init() {
        tbCneterTv.setText("首页");
        bottomNavigationBar
                .addItem(new BottomNavigationItem(R.mipmap.viewgallery, "Home"))
                .addItem(new BottomNavigationItem(R.mipmap.atm, "Chat"))
                .addItem(new BottomNavigationItem(R.mipmap.favorite, "Favorite"))
                .addItem(new BottomNavigationItem(R.mipmap.personal_center, "Mine"))
                .initialise();
        bottomNavigationBar.setTabSelectedListener(this);
        fragments[0] = HomeFragment.newInstance();
        fragments[1] = ChatFragment.newInstance();
        fragments[2] = FavoriteFragment.newInstance();
        fragments[3] = MineFragment.newInstance();
//        Rigger.getRigger(this).addFragment(R.id.id_content, fragments);
//        Rigger.getRigger(MainActivity.this).startFragment(fragments[0]);
    }
`

**Comment by JustKiddingBaby** [comment]
@chenbaige 不好意思，这应该不属于本框架的错误，方便的话你可以把你的demo发我邮箱进行错误排查.

**Comment by AndroidJohnsonWang** [comment]
遇到同样问题，没安装任何第三方插件
