### ISSUE TITLE
com.jkb.fragment.rigger.b.c: UnKnown error MainActivity@41919b78 is not added into rigger. please check your config or contact author.

### ISSUE THREAD

**Issue by yqzGitHub** [JustKiddingBaby/FragmentRigger#54]
想在Android module中使用，出现以下错误，请帮忙看下什么情况。
E: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{MainActivity}: com.jkb.fragment.rigger.b.c: UnKnown error MainActivity@41919b78 is not added into rigger. please check your config or contact author.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
        at android.app.ActivityThread.access$800(ActivityThread.java:138)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5095)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.jkb.fragment.rigger.b.c: UnKnown error MainActivity@41919b78 is not added into rigger. please check your config or contact author.
        at com.jkb.fragment.rigger.rigger.Rigger.getRigger(Unknown Source)
        at MainActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
        at android.app.ActivityThread.access$800(ActivityThread.java:138) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5095) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by JustKiddingBaby** [comment]
@yqzGitHub  请贴出你的 gradle 配置

**Comment by WUSIR-ShiYan** [comment]
在gradle中配置：apply plugin: 'android-aspectjx' 就可以了
